### ISSUE TITLE
Hur ställer jag in mitt filmtipset username och password?

### ISSUE THREAD

**Issue by Sajjon** [Tigge/script.filmtipset-grade#1]
Hej

Jag har kopierat in mappen till /Applications/Kodi.app/contents/resources/addons
Och när jag avslutar en film så kommer rutan med rating upp, så ditt add-on fungerar :).

Men.... jag måste ju förstås lägga in mina användaruppgifter! Jag hittade settings.xml filen i din mapp, är det där jag ska lägga in uppgifterna, under default="VALUE_HERE"? Jag tror jag vet vad mitt user_id är, det är väl mitt medlemsnummer. Med vad är user key? Var hittar jag den? :)

För övrigt så hittar jag inte ditt add-on i Kodi, alltså bland menyerna, men det verkar ju iaf fungera, behöver bara veta hur jag hittar mitt user key :).

Tack!

mvh
Alex

**Comment by Tigge** [comment]
Av någon anledning så har jag inte fått en riktig API-nyckel av Filmtipset - nåt om att den i så fall skulle vara öppet tillgänglig för alla eftersom detta är en fri mjukvara, detta verkar inte vara ett problem för andra applikationer dock...

Du kan ändra i `service.py` här och byta `FILMTIPSET_ACCESS_KEY` till "xtyrZqwjC7I1AVrX5e0TOw" (som är access key för chrome-extensionen) och sedan gå in på http://nyheter24.se/filmtipset/api.cgi?keys=1 och skapa en nyckel (user key) för "pbolmsteds Chrome extension".

**Comment by Sajjon** [comment]
Hej,

Tack för snabbt svar :)

Okej så:
1) Ändra FILMTIPSET_ACCESS_KEY till xtyrZqwjC7I1AVrX5e0TOw i service.py 
2) Skapa API-nyckel för "pbolmsteds chrome extensino" på filmtipset sajten, detta är alltså user_key?
3) Använda API-nyckel/user_key i 2) i settings.xml filen
4) Starta om Kodi
5) klar?

Tack!

**Comment by Tigge** [comment]
Stämmer bra! Ska också gå att ställa in user_key och den biten i UI:t i Kodi om man hittar igen inställningarna för tillägget där.

**Comment by Sajjon** [comment]
Grymt tack då vet jag, sjukt bra add-on Gustav! :+1: 

Tror du att det är möjligt att hämta betyg-prognoser för filmer man inte sett? Vore AMAZING att ersätta tMDB rating med dessa.

Men de kanske inte är accessible via filmtipsets API?

Ang. hitta inställningarna för din add-on i Kodi, var hittar jag dem?! :P Jag hittar inte ens din add-on i Kodi, men den fungerar ju bevisligen :)

**Comment by Tigge** [comment]
Vet inte hur det är i Kodi faktiskt, har inte prova där men innan kunde man gå in på addons och leta upp den och sen där fanns inställningarna. Har slutat använda filmtipset och gått över till http://trakt.tv/ i stället men om jag minns rätt så ska betygsprognoser gå att hämta med API:et.

**Comment by Sajjon** [comment]
Okej tack så mycket!

Hmm jag känner inte till trakt.tv sen innan. Får du en siffra som prognos där också? Eller bara "vi tror du gillar detta" ? Du behöver inte betygsätta alltså? Utan man "scrobblar" som LastFm typ? :)

**Comment by Tigge** [comment]
Glömde bort följdfrågan :smile:. Det beror på vad man har för setup, men på Kodi så går det bra att scrobbla. Trakt är inte lika bra på att uppskatta vad man skulle gilla dock, det är nackdelen.
